version: "3.9"
services:
  user-service:
    container_name: user-service
    build:
      dockerfile: Dockerfile
      context: ./user-service
    env_file:
      - ./user-service/.env
    ports:
      - "8000:8000"
  user-service-db:
    container_name: user-service-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
